import Foundation

enum shimmerHavenBundle {
    static let folderName = "zedDigitalbaoamingtavens"
    static let zipPassword = "963258"
    static let fallbackImageName = "zedDigitalEylavenderEyelinermoodyLashLook.jpeg"

    static func targetDirectory(in baseDirectory: URL? = nil) -> URL {
        let base = baseDirectory ?? FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent(folderName, isDirectory: true)
    }

    static func localPath(for fileName: String, baseDirectory: URL? = nil) -> String {
        targetDirectory(in: baseDirectory).appendingPathComponent(fileName).path
    }

    static func exists(fileName: String, baseDirectory: URL? = nil) -> Bool {
        FileManager.default.fileExists(atPath: localPath(for: fileName, baseDirectory: baseDirectory))
    }
}

enum sparkleDiaryAsset {
    static let imageFolder = "LidLuImages"

    static let zippedImageNames = [
        "zedDigitalEyinteractiveMakeupExperienceInnovation.png",
        "zedDigitalEygelEyebrowPomadeSoftSmokeyEye.jpeg",
        "zedDigitalEymakeupBlindBoxAIeyelook.png",
        "zedDigitalEybeautyCommunityShareMatchselect.png",
        "zedDigitalEytexturedLashesfieryLidShade.jpeg",
        "zedDigitalEyeyelookAIDiscoveryuniqueBeauty.png",
        "zedDigitalEytrendspotterPlatform.png",
        "zedDigitalEyooInsooxselect.png",
        "zedDigitalEytintedBrowGelEyeContouring.jpeg",
        "zedDigitalEycopperEyeshadoweffortlessLashLift.jpeg",
        "zedDigitalEycyberGothAestheticHighFashion.png",
        "zedDigitalEybeautySparksbeautySparks.png",
        "zedDigitalEyglossyEyelinerpastelShadowTones.jpeg",
        "zedDigitalEybeautyAIStylisteyelookTrendsetterselect.png",
        "zedDigitalEymoodyLashLookelegantLashLook.jpeg",
        "zedDigitalEymakeupLookDiscoveryGalleryselect.png",
        "zedDigitalEymakeupInspirationPlatform.png",
        "zedDigitalEymakeupTrendSetterEyelooks.png",
        "zedDigitalEyholographicEyeshadsoftCutCrease.jpeg",
        "zedDigitalEynaturalEyeEnhancementnudeLidEffect.jpeg",
        "zedDigitalEynteractiveBeautyJourneyDesign.png",
        "zedDigitalEyshimmerEyeshadowcolorPopLine.jpeg",
        "zedDigitalEyplumEyeshadoweffortlessLashLift.jpeg",
        "zedDigitalEymakeupCustomizationPlatforms.png",
        "zedDigitalEylashLengtheningsubtleCrease.jpeg",
        "zedDigitalEycreativeMakeupDrivenMakeup.png",
        "zedDigitalEyeyelookRecommendationBlack.png",
        "zedDigitalEysmokeyEyeVibeslidGlowEffect.jpeg",
        "zedDigitalEybeautyCommunitymakeup.png",
        "zedDigitalEyeyelookMagicbeautySparks.png",
        "zedDigitalEydoubleWingedLinerBoldLashes.jpeg",
        "zedDigitalEythickLashCoatdeepBrowShape.jpeg",
        "zedDigitalEydeepBrowShapethickLashCoat.jpeg",
        "zedDigitalEymakeupTrendExplorationNavigator.png",
        "zedDigitalEymakeupCreationBoxTrendInsposelct.png",
        "zedDigitalEymakeupAITransBeautyJourney.png",
        "zedDigitalEybeautyCommunityShareMatch.png",
        "zedDigitalEymakeupCreativityHubLookDiscovery.png",
        "zedDigitalEysatinEyelinersoftCutCrease.jpeg",
        "zedDigitalEycreativeMakeupAIEnhancedEyelooks.png",
        "zedDigitalEycustomEyeStyleGeneratorAIStylistselect.png",
        "zedDigitalEyvirtualMakeupEyelooksselect.jpeg",
        "zedDigitalEysparklyBrowHighlightdeep.jpeg",
        "zedDigitalEyPencilLinermokeyEyeWingedLiner.jpeg",
        "zedDigitalEycreativeStyleBoxCollectionAI.png",
        "zedDigitalEyradiantEyeGlowholographicLashes.jpeg",
        "zedDigitalEymakeupTrendExplorationNavigatorselect.png",
        "zedDigitalEybeautyAIStylistzedEyeStyle.png",
        "zedDigitalEyEyelashExtensionsEyePrimer.jpeg",
        "zedDigitalEyconUnchecke.png",
        "zedDigitalEytrendyEyeLookstrendyEyeLooks.png",
        "zedDigitalEybeautyTrendIinnovativeEyelook.png",
        "zedDigitalEyaiDrivenMakeupvirtualMakeupArtist.png",
        "zedDigitalEycreativeMakeupEyelooks.png",
        "zedDigitalEypreciseBrowArchglossyEyelashes.jpeg",
        "zedDigitalEysoftCreaseBlenddelicateLashDefine.png",
        "zedDigitalEyeyeMakeupInCustomizationHub.png",
        "zedDigitalEycolorPopLinersoftSmokeyEyes.jpeg",
        "zedDigitalEyboldLashCurlwingedShadowStyle.jpeg",
        "zedDigitalEymonochromeEyesBoldBrows.png",
        "zedDigitalEyglobalMakeupGeneratorinnovativeselect.png",
        "zedDigitalEyfalseLashesCutCreasePencil.jpeg",
        "zedDigitalEycreativeInspoBoxbeautyTalks.png",
        "zedDigitalEymakeupMasterybeautyCraftsShare.png",
        "zedDigitalEyeyelookCreatorBoxSpirationFeedAI.png",
        "zedDigitalEyreativeBeautyFeedeyelookTransformation.png",
        "zedDigitalEyEyeshadowBasevFluffyLashes.jpeg",
        "zedDigitalEyroseGoldShadowlavenderEyeshadow.jpeg",
        "zedDigitalEybeautyCommunitySharermation.png",
        "zedDigitalEyeyelookAIStyleCreatorMakeupShare.png",
        "zedDigitalEylavenderEyelinermoodyLashLook.jpeg",
        "zedDigitalEycustomEyeMakeupMakeupInspo.png",
        "zedDigitalEymultiColoredLashesglimmeringBrowArch.jpeg",
        "zedDigitalEybeautyInspouniqueEyeLookCreator.png",
        "zedDigitalEymakeupExperienceBoxEyeStylist.png",
        "zedDigitalEydreamyEyeshadowPaletteeyelashFlick.jpeg",
        "zedDigitalEyaiDrivenMakeupLooksMakeupFeed.png",
        "zedDigitalEyeyeMakeupExplorerBeautyExperience.png",
        "zedDigitalEyinnovativeEyelookVisionAI.png",
        "zedDigitalEyeyeBrighteningEffectboldLashCurl.jpeg",
        "zedDigitalEyyelookStyleGeneratormation.png",
        "zedDigitalEyeyeMakeupIdeaBoxGeneratoreyeLog.png",
        "zedDigitalEyvirtualMakeupEyelooks.png",
        "zedDigitalEybeautyStyleNavigatorleInnovator.png",
        "zedDigitalEysoftShimmerLinerdefinedOuterCrease.jpeg",
        "zedDigitalEyeyeMakeupDesignermakeupExperienceB.png",
        "zedDigitalEybeautyAIStylistExchangePlatform.png",
        "zedDigitalEyformationStylingInspirationCreator.png",
        "zedDigitalEynaturalShadowBlendlashLiftEffect.jpeg",
        "zedDigitalEymakeupEyelookFeedCollectionAI.png",
        "zedDigitalEymakeupCreationBoxTrendInspo.png",
        "zedDigitalEyLookInspsdhasjdhoBox.png",
        "zedDigitalEyMaquiagemmasculinacarnava.jpeg",
        "zedDigitalEymakeupTrendForecastuniqueBeautyAI.png",
    //    "zedDigitalEyrichLidShadecleanEyelinerLine.png",
        "zedDigitalEydeepPlumEyelinersparklingBrowGleam.jpeg",
        "zedDigitalEydeepEyeshadowPigmentclearBrowGel.jpeg",
        "zedDigitalEybeautyInspoGeneratorAIStyleGuide.png",
        "zedDigitalEycreativeMakeupShowcase.png",
        "zedDigitalEymakeupArtistrybeautyDiscovery.png",
        "zedDigitalEymakeupInsporsonalizedEyeStyle.png",
        "zedDigitalEyeyeContourShapingwarmLidShade.jpeg",
        "zedDigitalEybeautyTrendTrackerpirationFeed.png",
        "zedDigitalEyangelicLashesglossyLashCoat.jpeg",
        "zedDigitalEyeyeMakeupMasterpiecemakeupAIInspo.png",
        "zedDigitalEyglitteryBrowEnhanceiridescentLidShade.jpeg",
        "zedDigitalEyinteractiveMakeupBeautyTribe.png",
        "zedDigitalEyglobalMakeupBeautyInspo.png",
        "zedDigitalEydramaticEyesGlitterLiner.jpeg",
        "zedDigitalEybeautyInspoHubVisionLooks.png",
        "zedDigitalEysparklyBrowHighlightdeepCutCrease.jpeg",
        "zedDigitalEyeyeMakeupBlenderAIStyledEyelookselset.png",
        "zedDigitalEyvirtualBeautyCommunityLooks.png",
        "zedDigitalEymakeupVisionAIBeautyLooks.png",
        "zedDigitalEyeeyeMakeupCreationBoxPlatform.png",
        "zedDigitalEyeyeMakeupBlenderAIStyledEyelooks.png",
        "zedDigitalEyransformationeyelookAIStyle.png",
        "zedDigitalEyniqueMakeupInspoVisionBox.png",
        "zedDigitalEybeautyAIStylisteyelookTrendsetter.png",
        "zedDigitalEycolorfulEyeshadowFluffyLashes.jpeg",
        "zedDigitalEyglobalMakeupImakeupLookVision.png",
        "zedDigitalEytrendspotterMakeupStyledMakeup.png",
        "zedDigitalEyMakeupToolkitookInspoFeed.png",
        "zedDigitalEymakeupArtistryBoxMakeupExchang.png",
        "zedDigitalEyglowyEyeshadowFinishglowy.png",
        "zedDigitalEymultiLayerEyeshadoweyeMakeup.jpeg",
        "zedDigitalEymakeupCreationbeautyLookInspiration.png",
        "zedDigitalEyelegantLashLookdefinedOuterCrease.jpeg",
        "zedDigitalEycleanEyelinerdeepCutCrease.jpeg",
        "zedDigitalEycreativeBeautyLooksTrendsetter.png",
        "zedDigitalEymutedEyelinerlushLashCurl.jpeg",
        "zedDigitalEyfavicon.png",
        "zedDigitalEymakeupDiscoveryMakeupGenerator.png",
        "zedDigitalEymakeupInspokInspoFeed.png",
        "zedDigitalEyshimmerBrowHighlightnudeLidFinish.jpeg",
        "zedDigitalEyJourneyMakeupglobalBeautyTribe.png",
        "zedDigitalEyookInsasxifvpoxs.png",
        "zedDigitalEyLeyelashFlickrichLidShadeNordstrom.jpeg",
        "zedDigitalEyyelookStyleGeneratormationselect.png",
        "zedDigitalEycreativeEyeLoomakeupInspoGallery.png",
        "zedDigitalEyapunchrcon.png",
        "zedDigitalEymakeupStyleCustomizerEyeMakeup.png",
        "zedDigitalEycustomEyeStyleGeneratorAIStylist.png",
        "zedDigitalEydefinedBrowShapeglossyEyeliner.jpeg",
        "zedDigitalEymakeupLookcreativeMakeupIdeas.png",
        "zedDigitalEystyleInnovationBoxbeautyTalks.png",
        "zedDigitalEyuniqueMakeupInspoAIStyleGuide.png",
        "zedDigitalEyeyeMakeupInspirationAIGenerator.png",
        "zedDigitalEyglossyEyelashessoftLashCurl.jpeg",
        "zedDigitalEycreativeMakeupGeneratormakeup.png",
        "zedDigitalEyvirtualMakeupEyelooksselect.png",
        "zedDigitalEybeautyCommunitySharermationselect.png",
        "zedDigitalEybeautyLookCollectionTrendsetterAI.png",
        "zedDigitalEycutCreaseEyeshadowNudeEyeshadow.jpeg",
        "zedDigitalEygradientEyeShadowrichLidShade.jpeg",
        "zedDigitalEyglobalMakeupGeneratorinnovative.png",
        "zedDigitalEyeyelookTransformationcreativeBeautyFeed.png",
        "zedDigitalEybeautyLookInspirationPredictor.png",
        "zedDigitalEyiconSetting.png",
        "zedDigitalEydelicateCutCreaseboldOuterLiner.jpeg",
        "zedDigitalEyeyelookInspirationShareConnection.png"
    ]

    static func resolvedLocalPath(_ fileName: String) -> String {
        shimmerHavenBundle.localPath(for: fileName)
    }
}
