-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwp534yCANrPv6ndz
ZBcqJB6vXNYdX/m8XeWbUjlsR9KgCgYIKoZIzj0DAQehRANCAATYnkL9G6iYnIti
ol7MVKfcKoASaaR2xK7oeIVVmH5MQmSgDBCUZEhZNXNALOJsUvi5Op7thJDA+dV7
IDFm0cUg
-----END PRIVATE KEY-----