workflows:
  ios-native-workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: zww
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.zww.app.cn.com
      vars:
        BUNDLE_ID: "com.zww.app.cn.com"
        XCODE_WORKSPACE: "Streperfoforming.xcworkspace"
        XCODE_SCHEME: "Streperfoforming"
      xcode: 16.1 # 建议保持在稳定版
      cocoapods: default
    scripts:
      - name: Set up provisioning profiles
        script: |
          # 关键修改：添加 --generate-default-provisioning-profile
          # 这会强制 Codemagic 联机检查你的 App ID 权限（包括 Push）并生成匹配的文件
          xcode-project use-profiles --generate-default-provisioning-profile
      
      - name: Build ipa for distribution
        script: |
          # 关键修改：移除 --archive-flags 中的手动签名参数
          # 只要 use-profiles 成功，build-ipa 会自动找到正确的描述文件
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      scripts:
        - name: Check for ipa and upload to pgy
          script: |
            ipa_path=$(find build/ios/ipa -name "*.ipa" | head -1)
            if [[ -z ${ipa_path} ]]; then
                echo "No .ipa were found"
                exit 1
            else
                echo "Uploading $ipa_path to Pgyer..."
                curl -F "file=@${ipa_path}" \
                     -F "_api_key=a0b0d9b21085264b0a16d0ceb6341d74" \
                     https://www.pgyer.com/apiv2/app/upload
            fi
