workflows:
  ios-native-workflow:
    name: iOS Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: zww
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.zww.app.cn.com
      vars:
        BUNDLE_ID: "com.zww.app.cn.com"
        XCODE_WORKSPACE: InFriends.xcworkspace # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "InFriends" # <-- Put the name of your Xcode scheme here
      xcode: 16.1
      cocoapods: default
#    cache:
#      cache_paths:
#        - ~/Library/Caches/CocoaPods
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install --repo-update
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
#      - name: Increment build number
#        script: |
#          cd $CM_BUILD_DIR
#          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
#          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: false
          failure: false
      scripts:
        - name: Check for ipa
          script: |
              ipa_path=$(find build -name "*.ipa" | head -1)
              if [[ -z ${ipa_path} ]]
              then
                  echo "No .ipa were found"
              else
                  echo "start upload .ipa to pgy"
                  curl -F "file=@${ipa_path}" -F "_api_key=a0b0d9b21085264b0a16d0ceb6341d74" https://www.pgyer.com/apiv2/app/upload
              fi
            
