import Foundation

enum DMTPlateStamp {
    static let welcomeSplash = DMTStringCellar.shared.serve("art.welcomeSplash")
    static let houseNoteSeal = DMTStringCellar.shared.serve("art.houseNoteSeal")
    static let consentOff = DMTStringCellar.shared.serve("art.consentOff")
    static let consentOn = DMTStringCellar.shared.serve("art.consentOn")
    static let loginBanner = DMTStringCellar.shared.serve("art.loginBanner")
    static let loginMascot = DMTStringCellar.shared.serve("art.loginMascot")
    static let signUpCover = DMTStringCellar.shared.serve("art.signUpCover")
    static let hearthBackdrop = DMTStringCellar.shared.serve("art.hearthBackdrop")
    static let brandMark = DMTStringCellar.shared.serve("art.brandMark")
    static let noticeOrb = DMTStringCellar.shared.serve("art.noticeOrb")
    static let mealRobotBanner = DMTStringCellar.shared.serve("art.mealRobotBanner")
    static let createRoomButton = DMTStringCellar.shared.serve("art.createRoomButton")
    static let discoverComposer = DMTStringCellar.shared.serve("art.discoverComposer")
    static let rechargePromo = DMTStringCellar.shared.serve("art.rechargePromo")
    static let clipPublishOrb = DMTStringCellar.shared.serve("art.clipPublishOrb")
    static let audioModeBadge = DMTStringCellar.shared.serve("art.audioModeBadge")
    static let pictureModeBadge = DMTStringCellar.shared.serve("art.pictureModeBadge")
    static let focusOrb = DMTStringCellar.shared.serve("art.focusOrb")
    static let focusBadge = DMTStringCellar.shared.serve("art.focusBadge")
    static let reportOrb = DMTStringCellar.shared.serve("art.reportOrb")
    static let clipNoticeBubble = DMTStringCellar.shared.serve("art.clipNoticeBubble")
    static let actionLike = DMTStringCellar.shared.serve("art.actionLike")
    static let actionTalk = DMTStringCellar.shared.serve("art.actionTalk")
    static let tabRooms = DMTStringCellar.shared.serve("art.tabRooms")
    static let tabRoomsSelected = DMTStringCellar.shared.serve("art.tabRoomsSelected")
    static let tabBuzz = DMTStringCellar.shared.serve("art.tabBuzz")
    static let tabBuzzSelected = DMTStringCellar.shared.serve("art.tabBuzzSelected")
    static let tabMate = DMTStringCellar.shared.serve("art.tabMate")
    static let tabMateSelected = DMTStringCellar.shared.serve("art.tabMateSelected")
    static let tabNook = DMTStringCellar.shared.serve("art.tabNook")
    static let tabNookSelected = DMTStringCellar.shared.serve("art.tabNookSelected")
    static let editTasteButton = DMTStringCellar.shared.serve("art.editTasteButton")
    static let walletCard = DMTStringCellar.shared.serve("art.walletCard")
    static let giftCard = DMTStringCellar.shared.serve("art.giftCard")
    static let nookEmpty = DMTStringCellar.shared.serve("art.nookEmpty")
}
